//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencia
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Motivo { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
