//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id { get; set; }
        public int C_Year { get; set; }
        public int Mes { get; set; }
        public int MontoTotal { get; set; }
    }
}
