//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRRHH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salida
    {
        public int Id { get; set; }
        public int CodEmpleado { get; set; }
        public string TipoSalida { get; set; }

        [Required(ErrorMessage = "Debe ingresar un motivo")]
        public string Motivo { get; set; }

        [Required(ErrorMessage = "Debe ingresar una fecha")]
        public System.DateTime FechaSalida { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
